"use client";

import { useEffect } from "react";

import {
  Zap,
  TrendingUp,
  Lightbulb,
  ShieldCheck,
  AlertTriangle,
  Loader2,
  Sparkles,
  X,
} from "lucide-react";
import { useAppStore } from "@/store";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";

interface IdeaAnalysisPanelProps {
  ideaId: string;
  isOwnerOrAdmin: boolean;
}

export default function IdeaAnalysisPanel({
  ideaId,
  isOwnerOrAdmin,
}: IdeaAnalysisPanelProps) {
  const { analysisReport, isAnalysisLoading, analyzeIdea, clearAnalysis } =
    useAppStore();

  useEffect(() => {
    return () => clearAnalysis();
  }, [clearAnalysis]);

  if (!isOwnerOrAdmin) return null;

  const handleAnalyze = () => {
    analyzeIdea(ideaId);
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case "Positive":
        return "text-green-500 bg-green-500/10";
      case "Mixed":
        return "text-yellow-500 bg-yellow-500/10";
      case "Negative":
        return "text-red-500 bg-red-500/10";
      default:
        return "text-muted-foreground bg-muted";
    }
  };

  return (
    <div className="bg-card border border-border rounded-3xl p-6 shadow-sm overflow-hidden relative">
      {!analysisReport && !isAnalysisLoading && (
        <div className="py-10 flex flex-col items-center text-center space-y-4">
          <div className="h-16 w-16 bg-primary/5 rounded-full flex items-center justify-center">
            <Zap className="text-primary h-8 w-8" />
          </div>
          <div>
            <h3 className="text-lg font-bold">AI Impact Analysis</h3>
            <p className="text-sm text-muted-foreground max-w-xs mx-auto">
              Get professional insights into your idea&apos;s potential impact
              and areas for improvement.
            </p>
          </div>
          <Button onClick={handleAnalyze} className="gap-2 rounded-xl">
            <Sparkles size={16} />
            Analyze Now
          </Button>
        </div>
      )}

      {isAnalysisLoading && (
        <div className="py-20 flex flex-col items-center justify-center space-y-4">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p className="text-sm animate-pulse">
            Gathering insights and calculating impact...
          </p>
        </div>
      )}

      {analysisReport && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="space-y-8"
        >
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-xl font-bold flex items-center gap-2">
                <ShieldCheck className="text-primary" />
                Performance Report
              </h3>
              <p className="text-sm text-muted-foreground">
                Generated by EcoPulse AI
              </p>
            </div>
            <div
              className={`px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider flex items-center gap-2 ${getSentimentColor(analysisReport.sentimentAnalysis)}`}
            >
              <TrendingUp size={14} />
              {analysisReport.sentimentAnalysis} Sentiment
            </div>
          </div>

          {/* Impact Score Grid */}
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4">
              <div className="bg-muted/30 p-6 rounded-2xl border border-border">
                <div className="flex items-end justify-between mb-2">
                  <span className="text-sm font-medium text-muted-foreground">
                    Impact Score
                  </span>
                  <span className="text-3xl font-black text-primary">
                    {analysisReport.impactScore}%
                  </span>
                </div>
                <div className="h-3 w-full bg-muted rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${analysisReport.impactScore}%` }}
                    transition={{ duration: 1, ease: "easeOut" }}
                    className="h-full bg-primary"
                  />
                </div>
                <p className="mt-4 text-xs text-muted-foreground leading-relaxed italic">
                  {`"${analysisReport.overallInsight}"`}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 gap-4">
              <div className="space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                  <Lightbulb size={14} className="text-yellow-500" />
                  Key Strengths
                </h4>
                <div className="space-y-2">
                  {analysisReport.keyStrengths.map((s, i) => (
                    <div key={i} className="text-sm flex items-start gap-2">
                      <div className="h-1.5 w-1.5 rounded-full bg-green-500 mt-1.5 shrink-0" />
                      {s}
                    </div>
                  ))}
                </div>
              </div>

              <div className="space-y-3 pt-2">
                <h4 className="text-xs font-bold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                  <AlertTriangle size={14} className="text-primary" />
                  Suggestions
                </h4>
                <div className="space-y-2">
                  {analysisReport.improvementSuggestions.map((s, i) => (
                    <div key={i} className="text-sm flex items-start gap-2">
                      <div className="h-1.5 w-1.5 rounded-full bg-primary/50 mt-1.5 shrink-0" />
                      {s}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="pt-4 border-t border-border flex items-center gap-2">
            <Button
              variant="outline"
              onClick={handleAnalyze}
              size="sm"
              className="rounded-lg text-xs h-8"
            >
              Refresh Analysis
            </Button>
            <Button
              variant="ghost"
              onClick={clearAnalysis}
              size="sm"
              className="rounded-lg text-xs h-8 gap-1.5 text-muted-foreground hover:text-destructive hover:bg-destructive/10"
            >
              <X size={13} />
              Close
            </Button>
          </div>
        </motion.div>
      )}
    </div>
  );
}
